# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
source /usr/share/doc/git-1.7.1/contrib/completion/git-completion.bash
PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '
